---

galaxy_info:
  author: Greg Rehm
  description: MEG server deployment role
  license: GPL
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  categories:
    - system

dependencies:
  - { role: ANXS.postgresql }
  - { role: DavidWittman.redis }
  - { role: ANXS.nginx }
