---

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart sks
  service: name=sks state=restarted

- name: restart megserver
  supervisorctl: name=megserver state=restarted

- name: restart celery
  supervisorctl: name=megserver_celery state=restarted
