
- name: install sks
  apt: name=sks
  notify:
    - restart sks

##############FIX ME####################
#Needs to cleanly handle failed_when and changed_when
#Was not tested
- name: build sks
  command: sks build
  register: build_sks_result
  failed_when: "'error' in build_sks_result.stderr"
  changed_when: False
  notify:
    - restart sks
########################################

- name: change ownership of sks files
  file: path=/var/lib/sks/DB owner=debian-sks group=debian-sks recurse=yes
  notify:
    - restart sks

- name: setup /etc/default/sks
  copy: src=sks dest=/etc/default/sks
  notify:
    - restart sks
